### PR TITLE
[WIP] poll states during heartbeat

### PR DESCRIPTION
**Pull request by dumpfheimer**
[WIP] poll states during heartbeat

Depends on https://github.com/pawlizio/pyvlx/pull/6

### CODE REVIEW

**Comment by pawlizio** [comment]
Is that ready for merge?

**Comment by dumpfheimer** [comment]
Sorry for the late response, was away from my computer.

I have been using this for quite some time without any issues, but it is more or less untested.

**Comment by pawlizio** [comment]
Ok, was just asking as it is titled as WIP

**Comment by dumpfheimer** [comment]
Yeah, I was not sure how to proceed. I have been running the code without issues for some time but I was away and would have not been able to help / clean up my mess if anything went south.

Maybe you could test the code in your setup and if you do not see any issues, I would say lets go ahead and merge.

**Pull request merged**
